apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    # Add your node IAM role here
    - rolearn: arn:aws:iam::<account-id>:role/<node-instance-role>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::985809756777:user/rishikesh
      username: rishikesh
      groups:
        - system:masters