trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'
  AWS_ACCESS_KEY_ID: $(awsAccessKeyId)
  AWS_SECRET_ACCESS_KEY: $(awsSecretAccessKey)
  AWS_REGION: 'us-east-1'

steps:
  - task: UseTerraform@0
    inputs:
      terraformVersion: $(TF_VERSION)

  - script: |
      terraform init
    displayName: 'Terraform Init'

  - script: |
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
